version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "battingai"
s3_bucket = "battingai-deployment-bucket-123456"
s3_prefix = "battingai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true